#!/usr/bin/env python3
"""
CRITICAL: Fix mode configuration to PREVENT mock data leakage

The issue: manual_override is set to "paper_mock" when it should be "paper_real" or "live"
This causes mock data to potentially contaminate historical mode
"""

import json
import sys

print("\n" + "="*70)
print("🔧 FIXING MODE CONFIGURATION")
print("="*70)

# Read current config
try:
    with open('.mode_config.json') as f:
        config = json.load(f)
except Exception as e:
    print(f"❌ Error reading config: {e}")
    sys.exit(1)

print("\n📋 CURRENT CONFIGURATION:")
print(f"  Mode: {config.get('mode')}")
print(f"  Manual Override: {config.get('manual_override')}")
print(f"  Date: {config.get('date')}")
print(f"  Speed: {config.get('speed')}")

# Determine correct manual_override based on mode
mode = config.get('mode', 'live')

if mode == 'historical':
    # In historical mode, should use 'paper_real' (simulated with real historical data, no mock)
    correct_override = 'paper_real'
    reason = "Historical mode should use REAL historical data, not mock"
elif mode == 'live':
    # In live mode, use 'live' or 'paper_real'
    correct_override = 'live'
    reason = "Live mode should use real live trading data"
else:
    # Default to paper_real (safe mode)
    correct_override = 'paper_real'
    reason = "Unknown mode, defaulting to safe paper_real"

print(f"\n🔍 ANALYSIS:")
print(f"  Current: {config.get('manual_override')}")
print(f"  Correct: {correct_override}")
print(f"  Reason: {reason}")

# Check if needs fixing
if config.get('manual_override') != correct_override:
    print(f"\n⚠️  MISMATCH DETECTED!")
    print(f"  This could cause mock data to leak into {mode} mode!")
    
    # Fix it
    config['manual_override'] = correct_override
    
    with open('.mode_config.json', 'w') as f:
        json.dump(config, f, indent=2)
    
    print(f"\n✅ FIXED!")
    print(f"  Updated manual_override to: {correct_override}")
    
    print(f"\n📝 NEW CONFIGURATION:")
    print(f"  Mode: {config.get('mode')}")
    print(f"  Manual Override: {config.get('manual_override')} ✅ CORRECTED")
    print(f"  Date: {config.get('date')}")
    print(f"  Speed: {config.get('speed')}")
else:
    print(f"\n✅ Configuration is correct!")

print("\n" + "="*70)
print("💡 MODE REFERENCE:")
print("="*70)
print("""
VALID CONFIGURATIONS:

Historical Mode (Testing with historical data):
  - Mode: "historical"
  - Manual Override: "paper_real"
  - Date: "2026-01-28"
  - Data: Uses 375 candles from Redis (45k BankNifty price)
  - Ticks: Injected by historical replay service
  - Result: NO MOCK DATA, only real historical data

Live Mode (Real trading):
  - Mode: "live"
  - Manual Override: "live"
  - Date: N/A
  - Data: Real Zerodha API data
  - Ticks: Real market ticks from Kite WebSocket
  - Result: Real live trading data

Mock Mode (Testing with mock data):
  - Mode: "mock"
  - Manual Override: "paper_mock"
  - Date: N/A
  - Data: Synthetically generated mock data
  - Ticks: Generated by mock_data_publisher.py
  - Result: Complete mock environment for testing

⚠️  DO NOT MIX MODES!
  - Don't use manual_override: "paper_mock" with mode: "historical"
  - Don't use manual_override: "live" with mode: "mock"
  - Each mode must have its corresponding override
""")

print("\n" + "="*70)
print("🚀 NEXT STEPS:")
print("="*70)
print("""
1. Verify fix worked:
   cat .mode_config.json

2. Restart services to apply changes:
   docker-compose restart market-data-api
   docker-compose restart market-data-dashboard

3. Verify historical data still shows:
   python verify_historical_data.py

4. Check dashboard for correct 28 Jan 2026 data
""")
