"""System Context Management for Run Isolation and Cache Management.

This module provides system-wide context management to ensure proper isolation
between different runs, modes (live/backtest), and prevent stale data interference.
"""

import os
import uuid
from datetime import datetime, timedelta
from typing import Dict, Any, Optional
from dataclasses import dataclass
import logging

logger = logging.getLogger(__name__)


@dataclass
class SystemContext:
    """System-wide context for run isolation and mode management."""

    run_id: str
    mode: str  # 'live', 'backtest'
    session_id: str
    start_time: datetime
    config: Dict[str, Any]

    @classmethod
    def create(cls, config: Optional[Dict[str, Any]] = None) -> 'SystemContext':
        """Create a new system context for this run."""

        if config is None:
            config = {}

        # Determine mode from environment or config
        mode = os.getenv("TRADING_MODE", config.get("mode", "live"))
        if mode not in ["live", "backtest"]:
            raise ValueError(f"Invalid mode: {mode}. Must be 'live' or 'backtest'")

        # Generate run ID
        run_id = str(uuid.uuid4())[:8]

        # Session ID for grouping related runs
        session_id = os.getenv("SESSION_ID", config.get("session_id", run_id))

        return cls(
            run_id=run_id,
            mode=mode,
            session_id=session_id,
            start_time=datetime.now(),
            config=config
        )

    def get_cache_key(self, base_key: str) -> str:
        """Generate namespaced cache key for this run."""
        return f"{self.mode}:{self.run_id}:{base_key}"

    def get_db_filter(self) -> Dict[str, Any]:
        """Get MongoDB filter for this run's data."""
        return {
            "run_id": self.run_id,
            "mode": self.mode
        }

    def get_metadata(self) -> Dict[str, Any]:
        """Get metadata to attach to all data generated by this run."""
        return {
            "run_id": self.run_id,
            "mode": self.mode,
            "session_id": self.session_id,
            "generated_at": self.start_time.isoformat(),
            "version": "1.0"
        }


class CacheManager:
    """Manages Redis cache with run isolation and cleanup."""

    def __init__(self, context: SystemContext, redis_client=None):
        self.context = context
        self.redis_client = redis_client

    def _get_redis_client(self):
        """Lazy load Redis client."""
        if self.redis_client is None:
            from .api_service import get_redis_client
            self.redis_client = get_redis_client()
        return self.redis_client

    def set(self, key: str, value: Any, expire_seconds: Optional[int] = None):
        """Set cache value with run namespacing."""
        full_key = self.context.get_cache_key(key)
        redis_client = self._get_redis_client()

        if expire_seconds:
            redis_client.setex(full_key, expire_seconds, value)
        else:
            redis_client.set(full_key, value)

    def get(self, key: str) -> Optional[Any]:
        """Get cache value with run namespacing."""
        full_key = self.context.get_cache_key(key)
        redis_client = self._get_redis_client()
        return redis_client.get(full_key)

    def delete(self, key: str):
        """Delete cache key with run namespacing."""
        full_key = self.context.get_cache_key(key)
        redis_client = self._get_redis_client()
        redis_client.delete(full_key)

    def cleanup_old_cache(self):
        """Clean up cache from previous runs in same mode."""
        try:
            redis_client = self._get_redis_client()

            # Find all keys for this mode
            pattern = f"{self.context.mode}:*"
            all_keys = redis_client.keys(pattern)

            keys_to_delete = []
            for key in all_keys:
                key_str = key.decode() if isinstance(key, bytes) else key
                # Delete keys that don't match current run_id
                if not key_str.startswith(f"{self.context.mode}:{self.run_id}:"):
                    keys_to_delete.append(key_str)

            if keys_to_delete:
                redis_client.delete(*keys_to_delete)
                logger.info(f"Cleaned up {len(keys_to_delete)} old cache keys for mode {self.context.mode}")

        except Exception as e:
            logger.warning(f"Failed to cleanup old cache: {e}")

    def get_run_stats(self) -> Dict[str, Any]:
        """Get statistics about cache usage for this run."""
        try:
            redis_client = self._get_redis_client()
            pattern = f"{self.context.mode}:{self.context.run_id}:*"
            keys = redis_client.keys(pattern)

            return {
                "run_id": self.context.run_id,
                "mode": self.context.mode,
                "cache_keys": len(keys),
                "start_time": self.context.start_time.isoformat()
            }
        except Exception as e:
            logger.warning(f"Failed to get run stats: {e}")
            return {}


# Global system context - initialized at startup
_system_context: Optional[SystemContext] = None
_cache_manager: Optional[CacheManager] = None


def get_system_context() -> SystemContext:
    """Get the global system context."""
    global _system_context
    if _system_context is None:
        _system_context = SystemContext.create()
        logger.info(f"SystemContext initialized: run_id={_system_context.run_id}, mode={_system_context.mode}")
    return _system_context


def get_cache_manager() -> CacheManager:
    """Get the global cache manager."""
    global _cache_manager
    if _cache_manager is None:
        context = get_system_context()
        _cache_manager = CacheManager(context)
        # Clean up old cache on initialization
        _cache_manager.cleanup_old_cache()
        logger.info("CacheManager initialized and old cache cleaned")
    return _cache_manager


def reset_system_context():
    """Reset system context (for testing or restart)."""
    global _system_context, _cache_manager
    _system_context = None
    _cache_manager = None


def cleanup_old_data():
    """Clean up data older than retention period (7 days as requested)."""
    try:
        from .api_service import get_mongo_client
        import os

        mongo_client = get_mongo_client()
        db_name = os.getenv("MONGODB_DATABASE", "zerodha_trading")
        db = mongo_client[db_name]

        # Calculate cutoff date (7 days ago)
        from datetime import datetime, timedelta
        cutoff_date = datetime.now() - timedelta(days=7)

        collections_to_clean = [
            "signals",
            "agent_discussions",
            "orchestrator_decisions"
        ]

        total_deleted = 0
        for collection_name in collections_to_clean:
            try:
                collection = db[collection_name]
                # Delete documents older than 7 days
                result = collection.delete_many({
                    "generated_at": {"$lt": cutoff_date.isoformat()}
                })
                deleted_count = result.deleted_count
                total_deleted += deleted_count
                if deleted_count > 0:
                    logger.info(f"Cleaned up {deleted_count} old documents from {collection_name}")
            except Exception as coll_err:
                logger.warning(f"Failed to cleanup collection {collection_name}: {coll_err}")

        logger.info(f"Data cleanup completed: {total_deleted} total documents removed (7+ days old)")

    except Exception as e:
        logger.error(f"Failed to cleanup old data: {e}")


# Run cleanup on module import
try:
    cleanup_old_data()
except Exception as e:
    logger.warning(f"Initial data cleanup failed: {e}")